try:
  print(1)
except:
  print("An exception occurred")